### ISSUE TITLE
Consider the baseline implementation.

### ISSUE THREAD

**Issue by mikependon** [rdagumampan/yuniql#1]
Consider these objects.

	**v0**
		Tables
		StoredProcedures
		Functions
		Triggers
		Views
		Storage
			DataFiels
			FileGroups
		Types
		Schemas

**Comment by rdagumampan** [comment]
Still investigating this feature. I think baselining happens very rare and usually only relevant when setting version control mechanism to schema on an existing databases. 

For greenfield or new databases, devs ussually start from their preferred design tool such as (SQL Management Studio Table Designer, SqlAlchemy, Sparx EA or other DB modelling tools). Then they extract the scripts, cleanup and arrange to create v0.00 of the schema. 

For existing database, we also variety of tools to extract the schema to form baseline. SQL Server Data Tools or we can generate via Generate Scripts in SSMS. Microsoft also release `mssql-scripter` a python based scripting tool.

To achieve this feature grammatically, I am looking at various possibilities:
- Sql Server SMO (NetStandard release available)
- mssql-scripter
- Custom script extraction code

Will keep this channel updated if I have progress

**Comment by rdagumampan** [comment]
This is marked as experimental feature and is now available for preview here
https://github.com/rdagumampan/yuniql/wiki/How-to-baseline-your-database#yuniqlx-baseline

```bash
yuniqlx baseline -c <your-source-database-connection-string> -p <your-v0.00-directory-path>
```

You would need to use `yuniql` to initialize your local workspace. For how-to guide, click here
https://github.com/rdagumampan/yuniql/wiki/Getting-started

HTH/Rodel
