### ISSUE TITLE
Support --no-transaction in yuniql run

### ISSUE THREAD

**Issue by rdagumampan** [rdagumampan/yuniql#110]
There are scripts that have to be outside of the transaction for reasons such when it doesn't make sense to do so or due to technical limitation of the target platforms. We can achieve this by accepting `--no-transaction` parameter and this would the migration without transaction.

```
yuniql run -t "v1.01-super-big-version" --no-transaction
```

**Comment by rdagumampan** [comment]
Related to #131

**Comment by TaurahSP** [comment]
@rdagumampan  i did create a new function that do not use transaction in my pull request for issue #115 due to limitations.

**Comment by rdagumampan** [comment]
Closing and implemented in master.  Will be part of release `v1.1-01.27.2021`.
Thanks @TaurahSP! This feature is merged with feature `--tranasction-mode session|version|none`
