### ISSUE TITLE
Drop database with yuniql destroy --force

### ISSUE THREAD

**Issue by rdagumampan** [rdagumampan/yuniql#115]
Dropping database is practical solution when running integration tests in a non-containerized environments. While we have `yuniql erase` to clean up the database of created objects, this reserved the database for single use. An alternative is to allow users to auto-create/drop database during deployment pipeline execution. 

### Strategy
yuniql doesn't auto create scripts for users but instead leaves this responsibility to the developers the right and compatible scripts. This is the case for `erase` and will be the same approach for `drop`. This means we need to have  `_drop` directory along side with `_init`, `_erase` and other directories. Users can drop an `.sql` file here which will be executed when `yuniql drop` is called.

To avoid mistakes, users have to send a `--force` command to reconfirm the intend of the command.

```
yuniql destroy --force
```

**Comment by TaurahSP** [comment]
@rdagumampan  can i take this one?

**Comment by rdagumampan** [comment]
Done. This feature will part of future release and available as `yuniql destroy --force` command.

```bash
docker run --rm -dit -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=P@ssw0rd!" -p 1400:1433 -d mcr.microsoft.com/mssql/server:2017-latest

SETX YUNIQL_CONNECTION_STRING "Server=localhost,1400;Database=helloyuniql;User Id=SA;Password=P@ssw0rd!"
SETX YUNIQL_WORKSPACE "C:\play\yuniql\samples\basic-sqlserver-sample"
SETX YUNIQL_PLATFORM "sqlserver" 

yuniql run -a --debug
yuniql list --debug
yuniql destroy --force --debug

```
