### ISSUE TITLE
Fail migrations when _draft directory is not empty and support --require-cleared-draft

### ISSUE THREAD

**Issue by rdagumampan** [rdagumampan/yuniql#122]
The `_draft` directory serve to contain repeatable migrations that has not graduated yet to an official version. This is the case for users who are still working on a script and would like to be executed everytime he commits changes to the repo. When the changes are final, it must be placed to an official version. This ensure the changes will be applied to target database immutably. 

For this to work, we need to validate that `_draft` directory must be emptied when approving changes in the CI/CD pipelines. A solution is to support `--require-cleared-draft`.

```
yuniql run --require-cleared-draft
```

**Comment by wcontayon** [comment]
Hi @rdagumampan can I submit a PR on this issue ?

**Comment by rdagumampan** [comment]
Closing. Will be part of release `v1.1-01.27.2021`.
Thanks again @wcontayon for this great contribution!
