### ISSUE TITLE
Improve parameter validation and error messages

### ISSUE THREAD

**Issue by rdagumampan** [rdagumampan/yuniql#135]
When running yuniql the first time and some mandatory parameters are missing because its not present in the environment variable or in the CLI parameter the migration fails with unfriendly error messages. To improve this, the message must be descriptive enough to help user know what needs to be done.

This example shows very cryptic error when the connection string is correct format. Error message "*Format of the initialization string does not conform to specification starting at index 0*"
```
C:\play\yuniql\samples\sqlserver-adventureworkslt2016-sample>yuniql run -c "use-this-connection-string"
Running yuniql v1.0.1 for windows-x64
Copyright 2019 (C) Rodel E. Dagumampan. Apache License v2.0
Visit https://yuniql.io for documentation & more samples

INF   2020-07-01 21:38:58Z   Started migration from C:\play\yuniql\samples\sqlserver-adventureworkslt2016-sample.
INF   2020-07-01 21:38:58Z   No explicit target version requested. We'll use latest available locally v0.01 on C:\play\yuniql\samples\sqlserver-adventureworkslt2016-sample.

ERR   2020-07-01 21:38:58Z   Failed to execute run function. Arrg... something seems broken.
Internal error message: Format of the initialization string does not conform to specification starting at index 0. .
If you think this is a bug, please report an issue here https://github.com/rdagumampan/yuniql/issues.

C:\play\yuniql\samples\sqlserver-adventureworkslt2016-sample>
```

A better message would be "*Missing parameter or incorrect format:  connectionString. When running from CLI, you need to pass `-c {your-connection-string} ` or `--connection-string {your-connection-string}`. If you need help formatting the connection string, visit https://www.connectionstrings.com*."

**Comment by TaurahSP** [comment]
Hi, can i take this issue.

**Comment by rdagumampan** [comment]
Hi @TaurahSP , thanks for your interest in yuniql and welcome :) yes please do. You can also see wiki pn how to prep you environment. If you need help just drop a message.

**Comment by rdagumampan** [comment]
Thanks again @TaurahSP. Improvement will be part of next release.
