### ISSUE TITLE
Run Yuniql failed with exit code 1

### ISSUE THREAD

**Issue by TanmayNaik17** [rdagumampan/yuniql#138]
Hi Rodel,

I am getting below error:

-ERR   2020-08-17 10:56:32Z   Failed to execute run function. Arrg... something seems broken.
2020-08-17T10:56:32.0616948Z Internal error message: Could not find a part of the path 'C:\home\DevTemp'. .

yuniql/error: The process 'C:\agent\_work\_tool\yuniql\0.0.0\x64\yuniql.exe' failed with exit code 1

Could you please suggest me what i am doing wrong. Any help is much appreciated.

My objective is to deploy Create table  script from devops devazure Build pipeline to Postgreql(Hadoop cluster) onPremises instance.

**Comment by rdagumampan** [comment]
Hi @TanmayNaik17, if you are using YAML pipelines, it would help if you can paste your pipelines here. The way yuniql works, it requires that you create a git repository it a compatible structure or create one first locally using yuniql CLI. Then you have to commit this into a git repo and use the git repo in your pipelines. This is an old guide but would still be able to give you the step by step in preparing a local repo.

https://github.com/rdagumampan/yuniql/wiki/Working-with-yuniql-and-git-repository

You can also refer to the samples available here https://github.com/rdagumampan/yuniql-tutorials/blob/master/yuniql-az-pipelines/azure-pipelines-multi-stage.yml

HTH

**Comment by TanmayNaik17** [comment]
Hi Rodel,

Below is YAML of RunYuiql task in my Azure pipeline. Input to to this task is nothing but postgresql corresponding create table script. (Is i am giving workspace directory in wrong way)

steps:
- task: rdagumampan.yuniql-azdevops-extensions.run-task.RunYuniqlCLI@1
  displayName: 'Run Yuniql'
  inputs:
    connectionString: '''Host=IpAddressofHost;Port=5432;Database=test_db;Username=abc;Password=abc'''
    workspacePath: /home/DevTemp
    targetPlatform: postgresql
    autoCreateDatabase: true

**Comment by rdagumampan** [comment]
@TanmayNaik17, I hope you are able find a way to fix this issue and appreciate if you can share with us. I suspect this was just simple case of wrong workspace path. Would help to test this with fully qualified path where your repo was checked out. Thanks for your feedback. Br, Rodel

**Comment by rdagumampan** [comment]
Closing due inactivity. Please reopen the issue should you need further support. Thanks for reaching out. HTH/Rodel
