### ISSUE TITLE
does yuniqlx support baselining from PostgreSQL?

### ISSUE THREAD

**Issue by csaket** [rdagumampan/yuniql#143]
I am interested in trying this out with my existing PostgreSQL database but the documentation is not clear if yuniqlx supports baselining from an existing PostgreSQL database.
Thanks

**Comment by rdagumampan** [comment]
@csaket thanks for your interest with yuniql. 

No, the baselining with yuniqlx only works with SqlServer and it was experimental work I did in the very beginning. I decided to let go of this feature as its quite complicated to adapt the always changing versions of various database platforms plus its facility we're likely to use less often.

If you still decided to try yuniql, just ping me so if you run into hiccups. Happy to support you.

P.S. Appreciate if you can drop a Star if you haven't done yet :)

**Comment by csaket** [comment]
Thank you for the quick response.
Do you know of any baselining tool that can work with PostgreSQL?
I want to use that as a first step to use yuniql

Thanks

**Comment by rdagumampan** [comment]
@csaket, I think you can export your pgsql schema using plain pgAdmin. You are also welcome to try other alternatives such as Flyway or maybe Liquibase.

**Comment by rdagumampan** [comment]
Closing due inactivity. Please reopen the issue should you need further support. Thanks for reaching out. HTH/Rodel
