### ISSUE TITLE
 Unable to locate executable file: 'powershell'.

### ISSUE THREAD

**Issue by DaltonBuy** [rdagumampan/yuniql#146]
I got this error. 

Unable to locate executable file: 'powershell'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.

do you have some idea, why or what is causing this?

**Comment by rdagumampan** [comment]
Hi @DaltonBuy , thanks for reaching out. Can you share the commands you are trying to exexute. 

The error says you dont have powershell installer or its not mapped to your PATH environment variable. 

If you are trying to install yuniql, try other ways describe here https://yuniql.io/docs/install-yuniql/

hth/Rodel

**Comment by rdagumampan** [comment]
Closing this due to limited information to investigate. Should this remain relevant, please reopen with more details. Thanks for your feedback. Br, Rodel - Creator of yuniql.
