### ISSUE TITLE
Refactor all reserved directory names to use global constants RESERVED_DIRECTORY_NAME

### ISSUE THREAD

**Issue by rdagumampan** [rdagumampan/yuniql#153]
For greater maintainability, it would be beneficial to replace all magic strings representing the reserved directories and use a global constant class. This make changes in any of this strings easier and safer.

Suggested class name: RESERVED_DIRECTORY_NAME
Values:
- _init
- _pre
- _draft
- _post
- _erase
- _drop
- _transaction

**Comment by bymse** [comment]
Hi, @rdagumampan!

Can I take this one, please?

**Comment by rdagumampan** [comment]
@bymse , thanks for reaching out and appreciate your interest with yuniql. Yes, please take it. I've been doing major refactoring lately in the branch `transaction-mode`. I think its better if you make your changes here and later make a PR to this branch to avoid merge conflicts.

Enjoy holidays.

**Comment by rdagumampan** [comment]
Btw, this maybe able to help you get started https://github.com/rdagumampan/yuniql/wiki/Setup-development-environment
And if you run into issue, I'll try my best to help you (with delays) :)

**Comment by bymse** [comment]
@rdagumampan, not about this particular issue, but about refactoring: 

I assume it's still going, but I'd like to warn you that there is a difference in program behaviour. 
In `master` branch it's possible to setup `connectionString` with environment variable, but in `transaction-mode` it's not possible.

master: https://github.com/rdagumampan/yuniql/blob/master/yuniql-cli/CommandLineService.cs#L177.

After a bit of debugging I've found the thing:
there is [ConfigurationService.Initialize](https://github.com/rdagumampan/yuniql/blob/transaction-mode/yuniql-core/ConfigurationService.cs#L39) which get connection string from environment
however there is [using of this ConfigurationService.Initialize](https://github.com/rdagumampan/yuniql/blob/transaction-mode/yuniql-core/MigrationServiceBase.cs#L49)
and on the next line `configuration` is passed to `_dataService.Initialize`, but it's an original `configuration` (without value from environment as fallback). 
So problem is: connectionString value from in `ConfigurationService` isn't used in `IDataService`

Should I propose an issue or it's just development time problem?

**Comment by rdagumampan** [comment]
Hi, yes this branch has many changes and including handling of configuration. I'll be done by tommorow with changes consistent with master behaviour :)

**Comment by rdagumampan** [comment]
I hope I dont give you a hard start but if you hold back and wait for me changes until late tommorow, then it will all be fixed and would work just as master :)

I also decided to use a singleton configuration class and there will be no need to class migrationService.Initialize() before migrationService.Run()

You can still make the changes in this branch and ill do the merge should it creates conflicts in PR. Sorry for this.

**Comment by bymse** [comment]
It's fine. Actually, it was interesting to take a look and debug this. Thanks!)

**Comment by rdagumampan** [comment]
Closing and merged in master.  Will be part of release `v1.1-01.27.2021`.
Thanks again @bymse  for this great contribution! 👍
