### ISSUE TITLE
CSV files in `_draft` folder not imported

### ISSUE THREAD

**Issue by DavidHopkinsFbr** [rdagumampan/yuniql#165]
I had some CSV data files in my `_draft` folder, but yuniql ignores them until I moved them into a specific version folder.

**Comment by rdagumampan** [comment]
Thanks for letting me know, sounds like a bug. ill check today and check if there are tests covering this.

**Comment by rdagumampan** [comment]
Hmmm... _draft folder was originally intended to run repeatable scripts that gets executed for every run... supporting bulk import here might contradict this intent... maybe it was deliberate that cac import is not supported here. will check this sometime today ;)

**Comment by DavidHopkinsFbr** [comment]
Ah, I was thinking that `_draft` is mostly for testing scripts that are still under development, so that they can easily be re-run.

But bulk data imports are only idempotent if they match IDs and update any rows already present in the database - otherwise, running the import a second time fails because of the ID conflicts. 

I might need to rewrite my imports as SQL statements to work for "draft imports".

**Comment by rdagumampan** [comment]
yes, its for both. My thought is while its still work in progress and user continue to refine the script, it should be possibel to just run and run again effectively CRATE OR REPLACE the existing objects. This what i mean repeatable. pre and post are also repeatable script containers.

But this is on my limited experience more inputs and more brains on this would help refine this behaviour. appreicate any ideas for improvement.

**Comment by rdagumampan** [comment]
Closed. This will be supported in the next target release. Bulk csv files can now be placed inside non-version directories such as `_pre`, '_post', '_draft'. As this directories are repeatedly executed for every migration run, the user is responsible for handling potential duplicates or integrity issues if files are loaded multiple times.

Thanks again @DavidHopkinsFbr  for this feedback. //Rodel

**Comment by rdagumampan** [comment]
https://github.com/rdagumampan/yuniql/commit/7819395f4c6864a7dc7519415c363558cc455239
