### ISSUE TITLE
CSV import failed but yuniql recorded the migration as successful

### ISSUE THREAD

**Issue by DavidHopkinsFbr** [rdagumampan/yuniql#166]
When I tried to import some master data from CSV using yuniql, the import failed due to a datatype mismatch in my input data:

```
String '0' was not recognized as a valid Boolean.Couldn't store <0> in ToBeRemoved Column.  Expected type is Boolean. String '0' was not recognized as a valid Boolean.
```

None of the CSV data was imported. That's behaving as I would expect - I would want _all_ the master data to be imported in an atomic transaction (to validate referential integrity within the imported data), which leaves the database either modified or not, without partial imports.

But the `_yuniql` table recorded the migration as successful, without any error source diagnostics, which meant that even after fixing the data set and executing `yuniql run` again, it was not applied correctly.

![image](https://user-images.githubusercontent.com/49743077/104551127-3c6cf980-5671-11eb-812a-8ae08deecca6.png)

**Comment by rdagumampan** [comment]
Hi @DavidHopkinsFbr , thank you very much for this feedback and sorry you run into this issue. I assume you are running this against MySql? MySql have no support for full transactional DDL, so the default behavioir of yuniql is to execute each statement using implicit transaction leading to behaviour you saw. Ideally, when any sxript failed the version will be marked as failed and last error and last sxript that failed is recorded in the table.


To address this limitation, you can
put those DML scripts inside vxx.xx\_transaction folder. yuniql will interpret this as full transactional dml operations.

I planned to document these for each platform but i have yet to prioritize. Thanks again for this feedback.

Br, Rodel - via iphone




- [ ] ￼￼ creat

**Comment by DavidHopkinsFbr** [comment]
On further testing I'm having trouble reproducing it. Possibly the issue may have been that I added more files to a given vX.XX folder after running it the first time.

I will give the transaction folder option a go for the data import stage.

**Comment by DavidHopkinsFbr** [comment]
If each CSV files is imported in a separate transaction, is there a way to define the import order within a particular version number? If table `A` has a foreign key constraint that references table `B`, I would need to import table `B`'s data before importing table `A`'s data. Using table names as CSV file names doesn't present an obvious way to define the import order. At the moment I'm just using multiple v1.01, v1.02, v1.03 etc to explicitly manage the data precedence order.

**Comment by rdagumampan** [comment]
I working to make this experience better in next preview release this month. 

Btw, its '_transaction' folder inside 'vxx.02' folder. It has limitation though that it cant be mixed with other scripts so you have to move the DDL sxripts into vxx.01 to ensure the ddl has been good already.

When script failed, you will be asked to issue '--continue-after-failure' else it wont proceed. this flag assumes users fixed and manually execited the faulty script outside of yuniql. yuniql will skip this file and proceed with next script in the last failed version

HTH

**Comment by rdagumampan** [comment]
Ohh, afraid so far csv files does not support sequence scheme but it makes a strong feature to support this. This is lacking for now as it other platforms, bulk import disables referential checks by default.

**Comment by rdagumampan** [comment]
@DavidHopkinsFbr , in preparation for new release candidate I'd like to close this case now. The next release this week will close some of this gaps such as sequence number in bulk files. It will also have much richer information when migration fails

When `yuniql run` fails
![image](https://user-images.githubusercontent.com/5895952/105916301-faf52a80-6030-11eb-98b4-0eede8adfad4.png)

Display the last error with `yuniql list`
![image](https://user-images.githubusercontent.com/5895952/105916374-14967200-6031-11eb-820f-1c122f86a170.png)

Thanks for this input.
