### ISSUE TITLE
Force print sensitive data with --trace-sensitive-data

### ISSUE THREAD

**Issue by rdagumampan** [rdagumampan/yuniql#177]
Force print sensitive data with `--trace-sensitive-data`. When this parameter is specific in any of yuniql commmands, the log file must not redact the sensitive data such as connection string values.  This would help developer during dev test debugging.

**Comment by rdagumampan** [comment]
Btw, you may find this also interesting as its supporting the enhancements of logger
Support --trace-directory and --trace-silent parameters #101

**Comment by bobi591** [comment]
@rdagumampan dropping a comment. I will take a look at the #101, once I come with clear idea how to implement it will drop a comment there as well. :)

**Comment by rdagumampan** [comment]
It works really well, thanks @bobi591 

![image](https://user-images.githubusercontent.com/5895952/107115823-82cc0780-686f-11eb-9838-e9f088a7f7c1.png)
