### ISSUE TITLE
Test connectivity to target server with yuniql ping

### ISSUE THREAD

**Issue by rdagumampan** [rdagumampan/yuniql#178]
Migrations may fail on first run due to connectivity issues. Most common reasons for this are:
- Wrong or malformed connection string
- Firewall on target server
- Firewall on client machine
- Down target server

It would be nice to just make connectivity test to capture this before a migration run. Using `yuniql run` and `yuniql verify` is too heavy for this purpose.

```
yuniql ping -c <connection-string>
yuniql ping -c <connection-string> --trace-sensitive-data
```

**Comment by bobi591** [comment]
@rdagumampan dropping a comment. :) Tomorrow I am going to hunt for more things to do in this project. I really appreciate your help and explanations!
