### ISSUE TITLE
Support - Oracle

### ISSUE THREAD

**Issue by wahmedswl** [rdagumampan/yuniql#184]
Hi,
Is there any plan to support Oracle, there is Managed driver available and support .NetCore as well.

Thanks

**Comment by rdagumampan** [comment]
Hi @wahmedswl, thanks for reaching out. Yes, we have plans for Oracle but its little down the road as I thought maybe we prioritize cloud managed platforms. But... if I there's PR for Oracle, I'd certainly take time to bring the platform in. I may change mind as it sounds to me is a low hanging fruit :)

![image](https://user-images.githubusercontent.com/5895952/107415196-5a643780-6b13-11eb-8552-b595fefdc330.png)

HTH, Rodel

**Comment by wahmedswl** [comment]
Thats great to hear, will look into contributing it. Will study code a bit as checked multiple tools for Database change management. eg: https://docs.liquibase.com/home.html and http://sqitch.org/docs/manual/sqitchtutorial-oracle/

Thanks

**Comment by rdagumampan** [comment]
@wahmedswl , that would be cool. I prepared a contributing guide here and some instructions how to support a new platform. I assume it should be simple and you can refer to existing implementations on SqlServer and PostgreSql. 

Contributing guide here > https://github.com/rdagumampan/yuniql/wiki

HTHT, Rodel
