### ISSUE TITLE
One thing, currently script order is per File Name sort, sorting this way is not intuitive.

### ISSUE THREAD

**Issue by rdagumampan** [rdagumampan/yuniql#193]
One thing, currently script order is per File Name sort, sorting this way is not intuitive. 
```
var list = new List<string>(new[]{ "v1.1", "v11.1", "v2.1" });
Console.WriteLine(string.Join(",", list));
//v1.1,v11.1,v2.1

list.Sort();
Console.WriteLine(string.Join(",", list));
//v1.1,v11.1,v2.1
```

_Originally posted by @wahmedswl in https://github.com/rdagumampan/yuniql/issues/192#issuecomment-777375105_

**Comment by wahmedswl** [comment]
yes, this is issue and we should have proper sorting. eg: DateTime or Version sort etc

**Comment by wahmedswl** [comment]
Hi, is there anything that can be done to resolve this one? maybe behind flag etc or some sort of version schema that can be used that apply migration in order etc?

Thanks

**Comment by rdagumampan** [comment]
Hi @wahmedswl, can you try this release and let me know if it worka for you. https://github.com/rdagumampan/yuniql/releases/tag/v1.3.2
