### ISSUE TITLE
An assembly specified in the application dependencies manifest (yuniql.deps.json) was not found: AngleSharp

### ISSUE THREAD

**Issue by rdagumampan** [rdagumampan/yuniql#197]
```console
C:\temp>yuniql
Error:
  An assembly specified in the application dependencies manifest (yuniql.deps.json) was not found:
    package: 'AngleSharp', version: '0.12.1'
    path: 'lib/netstandard2.0/AngleSharp.dll'
```

**Comment by rdagumampan** [comment]
Resolved by deleting all temp folders under `C:\Users\rdagumampan\AppData\Local\Temp\.net`.

**Comment by pmelander** [comment]
> Resolved by deleting all temp folders under `C:\Users\rdagumampan\AppData\Local\Temp\.net`.

I had the same problem, resolved by this solution, thank you!

**Comment by rdagumampan** [comment]
> > Resolved by deleting all temp folders under `C:\Users\rdagumampan\AppData\Local\Temp\.net`.
> 
> I had the same problem, resolved by this solution, thank you!

Glad it helped ")

P.S. Please star our repo ICYMI. It goes a long way in getting better stats and helping more people discover this tool :) Thanks!
