### ISSUE TITLE
MSSQL/New version: SUSER_SNAME() throw an exception: String or binary data would be truncated.

### ISSUE THREAD

**Issue by nerub1an** [rdagumampan/yuniql#201]
There is an exception during the input new version in **__yuniql_schema_version** if the username length more than 32.

![image](https://user-images.githubusercontent.com/17453609/112484991-80742d00-8d8b-11eb-9428-ad7406a93312.png)

![image](https://user-images.githubusercontent.com/17453609/112484772-4acf4400-8d8b-11eb-9b11-ab2a47c1a5b9.png)

**Comment by rdagumampan** [comment]
@nerub1an , thanks for reaching out and your interest in yuniql. I would have chance to fix this soon but meanwhile, please hack the table to change the length of the column.

**Comment by rdagumampan** [comment]
Hi @nerub1an I had time to work on several issues including this one. In this case, I think its best that I adjust the future databases to be managed by yuniql. I apologize for this and you have to manually adjust the column size for now. In next release of yuniql v1.2, the user column is adjusted from 32 chars into 129 chars. Perhaps this is sufficient to cover even the edge cases :)
