### ISSUE TITLE
yunql.dll not found

### ISSUE THREAD

**Issue by avengerovsky** [rdagumampan/yuniql#209]
I ran successfully yuniql migrations couple weeks ago. Today it reported an error msg: 
The application to execute does not exist: 'C:\Users\venge\AppData\Local\Temp\.net\yuniql\k1uc1fr4.typ\yuniql.dll'.

The folder referenced above exists but it doesn't contain yuniql.dll
No changes on my machine that I can recall. 
Any guidance/thoughts?
Thanks,
Alex

**Comment by rdagumampan** [comment]
@avengerovsky, thanks for reaching out and I appreciate you're interest in using yuniql. Hmm... I think I've seen this issue before. Please try to delete the entire `Temp.net\yuniql` folder. It will fix itself on your next run. HTH/Rodel

**Comment by avengerovsky** [comment]
Thank  you for the prompt response! Your suggestion worked perfectly. Is
there anything I need to watch for, change to avoid hitting this problem in
the future?
again, much appreciated.
AV.

**Comment by rdagumampan** [comment]
Hi @avengerovsky, been away for long vacation but I hope you are doing well so far with the quick fix. I don't know yet the reason for this, possibly somethign to do with .NET Core caching behavior. Lets hope this doesnt happen when we upgrade yuniql to .NET 6. Thanks for your support and feedback! HTH/Rodel

**Comment by rdagumampan** [comment]
I am closing this issue for now.
