### ISSUE TITLE
Keyword not supported: 'port'.

### ISSUE THREAD

**Issue by darwinpasco25** [rdagumampan/yuniql#213]
![image](https://user-images.githubusercontent.com/16263712/131951708-988c2377-3094-4e5c-af85-38bebaeea214.png)

**Comment by rdagumampan** [comment]
Thanks for reaching out @darwinpasco25 . Try to include the port number in the `Server` such as `Server=localhost, 3308`. Let me know if this works or not.

**Comment by rdagumampan** [comment]
Closing due inactivity. Please reopen the issue should you need further support. Thanks for reaching out. HTH/Rodel
