### ISSUE TITLE
Assembly Error - Run Command Failure

### ISSUE THREAD

**Issue by Shaggstar** [rdagumampan/yuniql#218]
I have been unable to successfully execute a run command, I was able to yesterday but now when I try to update our database, whether my local copy or connecting to our AWS instance it fails with the same error. I suspect this relates to my yuniql instance however uninstalling/re-installing fails to remedy. Could someone kindly assist? 

command: yuniql run -c "Server=xx.xxxx.xx.xx;Port=12345;User Id=name;Password=xxx;Database=dbname" --platform "postgresql" -d -t "v0.0212" -a --environment test --command-timeout 0

Error: 

![image](https://user-images.githubusercontent.com/42647364/142698070-070e74ca-a8f3-4806-b4a3-9696ec683e56.png)

**Comment by rdagumampan** [comment]
Hi @Shaggstar , please refer to this
https://github.com/rdagumampan/yuniql/issues/197

HTH, Rodel
