### ISSUE TITLE
Migrate sqlserver driver to use Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by rdagumampan** [rdagumampan/yuniql#224]
Hi @farazfaheem, sorry for delayed response, been busy lately on python and databricks :). I have investigated this and it seems related to the SqlClient I used. The issue could be fixed if I use Microsoft.Data.SqlClient. It can also be fixed if I dont use the `SqlClient.SqlConnectionStringBuilder`. 

I dont have a fixed yet but as work around for now would be to use Sql Account. Please stay tune, I will pickup all these open bugs during my summer holiday in Mid May :)

_Originally posted by @rdagumampan in https://github.com/rdagumampan/yuniql/issues/199#issuecomment-829420881_

**Comment by smitvora10** [comment]
Can i help with this to solve this issue?

**Comment by rdagumampan** [comment]
This issue is related to:
#229 Setup Azure AD support
#199 Failed connecting to Azure Sql Database
#223 Upgrade solution to .NET 6 LTS

**Comment by smitvora10** [comment]
Ok Rodel i will see what i can do and get back to you.

**Comment by pmelander** [comment]
I have a Fork where I upgraded to Microsoft.Data.SqlClient and it seems to be working pretty straight forward. I was not able to get the tests running because of a locale issue, but I've successfully deployed to an Azure SQL Server using Active Directory Default authentication, which is not supported in System.Data.SqlClient

```powershell
[CmdletBinding(DefaultParameterSetName = 'None')]
param
(
  [String] [Parameter(Mandatory = $true)] $ServerName,
  [String] [Parameter(Mandatory = $true)] $Database
)

.\yuniql.exe run --connection-string "Server=tcp:$ServerName,1433;Database=$Database;Authentication=Active Directory Default" --auto-create-db --environment "DEV"
```
