### ISSUE TITLE
Why Core is linked to SqlServer ???

### ISSUE THREAD

**Issue by evilz** [rdagumampan/yuniql#241]
![image](https://user-images.githubusercontent.com/2937862/149312845-198d578d-68b3-49b1-8271-2735f64b8200.png)

**Comment by rdagumampan** [comment]
Hi @evilz, thanks for reaching out. Good catch, I had look back again as I thought I have cut this before. Historically, SqlServer is the default driver and the only driver supported. But it has evolve to support more platforms so this should not have been the case.

This shows, the default factory method is still there. Marking this as for improvement. I will see if I can make this part of next release I'm cooking v1.2. Also feel free to PR if you can.

![image](https://user-images.githubusercontent.com/5895952/149314360-e53cc41c-be21-45ac-9104-752ed609910e.png)

**Comment by rdagumampan** [comment]
https://github.com/rdagumampan/yuniql/commit/85b0ca37a1135e9b33a90358e8f8e508da3f0224

**Comment by rdagumampan** [comment]
Fixed. Dependency has been removed from Core and will be released as part of v1.2
https://github.com/rdagumampan/yuniql/commit/85b0ca37a1135e9b33a90358e8f8e508da3f0224
