### ISSUE TITLE
Directory names like v10.0.0 and higher versions are not taking as latest

### ISSUE THREAD

**Issue by virad3** [rdagumampan/yuniql#249]
For updating DB schema, SQL queries written in different directories with version names like v1.0.1, v2.2.3 so on. After v9.1.3 I have included a new directory called v10.0.0 but yuniql is not taking as the latest 
![image](https://user-images.githubusercontent.com/56317365/154631141-35d6d61a-168d-4e95-82be-4480948b81bc.png)

After run yuniql with the above directory structure it is only taking v9.0.0 as the latest even it is having v10.0.0
![image](https://user-images.githubusercontent.com/56317365/154631848-725efcd0-0277-4c05-9525-cab6309eeeaf.png)

Please provide a solution for this

**Comment by rdagumampan** [comment]
@virad3, looks like a major bug. I will look into this and keep you updated. Im about to release v1.2x this weekend so I hope this can make the cut.

**Comment by rdagumampan** [comment]
@virad3 , can you please try this pre-release out if this fixes all the issues you experienced. Appreciate if you can send the feedback soonest. Thanks for filing this issue.

You can down v1.2.25 release here.
https://github.com/rdagumampan/yuniql/releases/tag/latest

**Comment by virad3** [comment]
@rdagumampan, it worked. Thank you

**Comment by rdagumampan** [comment]
Close. Fix available in release v1.2.25.
