### ISSUE TITLE
Directory names like v0.00.1, v0.01.1, v0.02.1, v0.03.1 , It was working upto v0.02.1 but when I deployed v0.03.1 it was showing below error.

### ISSUE THREAD

**Issue by omptech** [rdagumampan/yuniql#252]
No explicit target version requested. We'll use latest available locally v0.03 , Failed to execute run function. Target version does not exist in the workspace directory. Check if you entered the correct version name. Directories can be case sensitive depend on the Operation System yuniql runs.
Diagnostics stack trace captured a Target version does not exist in the workspace directory. Check if you entered the correct version name. Directories can be case sensitive depend on the Operation System yuniql runs. 
If you think this is a bug, please report an issue here https://github.com/rdagumampan/yuniql/issues.

Note: I was using the latest version of yuniql that is [v1.2.25] which leads to above error but when I used the previous version  of yuniql that is [v1.1.55] and it was working fine. And It deployed the version v0.03.1 successfully.

**Comment by rdagumampan** [comment]
Thanks for reporting this. I thought this case has been covered by tests. I'll investigate and get back to you soonest.

P.S. Despite unpleasant experience, appreciate if you can drop a Star or Fork. Thank you.

**Comment by rdagumampan** [comment]
Hi @omptech , can you try this nightly build. I have also added more tests to cover all possible cases. Thanks for promptly reporting this issue. https://github.com/rdagumampan/yuniql/releases/tag/v1.2.31
