### ISSUE TITLE
Support for SQL Server 2016

### ISSUE THREAD

**Issue by Dave-Smith** [rdagumampan/yuniql#265]
The SQL Server documentation says that yuniql supports 2017 and later.  After looking thought the yuniql code I could find anything obvious that limits to 2017.  Are there any known limitations that would stop it from working on 2012 or 2016?

**Comment by rdagumampan** [comment]
Hi @Dave-Smith, thanks for reaching out. The limitations is based on fact that we have no platform tests executed against those versions. It may work just as well because the I tried to use older SQL syntax as much as possible. Please try if you have an instance and HTH

**Comment by Dave-Smith** [comment]
Thank you for your response.  This helps.  I tested ``yuniql init``, ``yuniql run``, ``yuniql check``, ``yuniql list``, ``yuniql verify`` and all worked on a 2016 database.
