### ISSUE TITLE
Official 1.3 release date

### ISSUE THREAD

**Issue by tech7857** [rdagumampan/yuniql#268]
Hi @rdagumampan 

wanted to check what is the official release date for 1.3.

Thanks

**Comment by tech7857** [comment]
@rdagumampan Thanks for letting us know. All the enhancements are great but I am specifically looking for #254

**Comment by rdagumampan** [comment]
Closed. Released in `v1.3.10`.
https://github.com/rdagumampan/yuniql/releases/tag/v1.3.10
