### ISSUE TITLE
Environment aware scripts

### ISSUE THREAD

**Issue by rdagumampan** [rdagumampan/yuniql#27]
Some scripts may only be applicable in specific environment. For example,you may want to create big tables with partition functions and partition schemes in PROD but not in DEV and TEST environment. You may name the file with `ENV.create_big_tables.sql`

`yuniql run -a --environment DEV`
`yuniql run -a --environment TEST`
`yuniql run -a --environment STAGING`
`yuniql run -a --environment PROD`

**Comment by mikependon** [comment]
Can you do it like this?

v1.0
	- storedprocedures
	- views
	- tables
	- schemas
	- _dev
		- storedprocedures
		- views
		- tables
		- schemas
	- _test
		- storedprocedures
		- views
		- tables
		- schemas
	- _staging
		- storedprocedures
		- views
		- tables
		- schemas
	- _prod
		- storedprocedures
		- views
		- tables
		- schemas

**Comment by rdagumampan** [comment]
Implemented.
https://github.com/rdagumampan/yuniql/wiki/Environment-aware-scripts

Environment-aware scripts are `sql` files that targets specific environment. For example,you may want to create big tables in Production with dedicated SQL Server file group, applies partition functions and partition schemes, customized index fill factor but you don't need this in Development and Test environments. Another example is applying permissions by script that's different in Non-Production and Production environments.

## Organize your repository
Any directory inside yuniql standard directories (`_init`,`_pre`,`_vxx.xx`,`_draft`,`_post`,`_erase`) that starts with underscore (`_`) represents an environment. To organize your repository, you may create `_dev`, `_test`, and `_prod` inside those directories or in any sub-directories.

Example #1: Organizes script by directory
```console
v1.00
+ _development
    - setup_tables.sql
+ _test
    - setup_tables.sql
+ _staging
    - setup_tables.sql
+ _production
    - setup_tables.sql
```

Example #1: Organizes script in sub-directory
```console
v1.00
+ setup-tables
  + _development
      - setup_tables.sql
  + _test
      - setup_tables.sql
  + _staging
      - setup_tables.sql
  + _production
      - setup_tables.sql
```

## Run migrations
Repositories organized with environment-aware scripts requires that environment code is pass during migration. Yuniql will throw exception and fail the migration when no environment code passed into CLI or API.

```console
yuniql run -a --environment DEVELOPMENT
yuniql run -a --environment TEST
yuniql run -a --environment STAGING
yuniql run -a --environment PRODUCTION
```

### Found bugs?
Help us improve further please [create an issue](https://github.com/rdagumampan/yuniql/issues/new).
