### ISSUE TITLE
CLI to run until mentioned version

### ISSUE THREAD

**Issue by farazfaheem** [rdagumampan/yuniql#71]
Hi, 
I think CLI should have a way to run until selected version. This is very helpful in testing scenarios on different versions to see how a system would behave. 

Such a feature is feasible specially when testing statistical data where business logic is stored in stored procedures.

something like **yuniql run -v v0.01**

**Comment by rdagumampan** [comment]
@farazfaheem, thanks for feedback.  This feature is available via `-t` parameter. For example

```console
yuniql run -c <connnection-string> -p <worspace-path> -t v1.01
```

If no target version passed, yuniql will run migration upto the latest local version available. You can access CLI parameters by this command.

```console
C:\temp>yuniql run --help
yuniql 0.355.0
Copyright 2019 Rodel E. Dagumampan

  -t, --target-version       Target version to migrate into and skipping versions greater.
  -a, --auto-create-db       (Default: false) Create database automatically.
  -k, --token                Replace tokens using the passed key-value pairs.
  --delimiter                (Default: ,) Bulk import file delimiter.
  --environment              Environment code for environment-aware scripts.
  --platform                 (Default: sqlserver) Target database platform.
  --plugins-path             The location of plugins. The default location is current location of the yuniql assemblies.
  -c, --connection-string    Connection string to target database server instance.
  --command-timeout          (Default: 30) The time in seconds to wait for the command to execute.
  -p, --path                 Path to initialize.
  -d, --debug                Print debug information including all raw scripts.
  --help                     Display this help screen.
  --version                  Display version information.
```

**Comment by farazfaheem** [comment]
Great...  thanks (Y)..

**Comment by rdagumampan** [comment]
@farazfaheem 

FYI, I have just release v0.465.0 this morning. This is a BETA RELEASE and maybe have breaking changes on your pipelines. Please refer to this release note and create ticket if you found an issue.

https://github.com/rdagumampan/yuniql/releases/tag/v0.465.0

Thanks for your interest with yuniql.
Cheers, Rodel
