### ISSUE TITLE
Example of the YUNIQL_CONNECTION_STRING

### ISSUE THREAD

**Issue by larsoleruben** [rdagumampan/yuniql#91]
Can I find an example of this anywhere?

**Comment by rdagumampan** [comment]
@larsoleruben  this is your best source of connection strings format for each platform
https://www.connectionstrings.com/

If you are using Azure Sql Database, there's a are to Copy the actuall connection string less the password.

HTH.

**Comment by rdagumampan** [comment]
@larsoleruben ,

FYI, I have just release v0.465.0 this morning. This is a BETA RELEASE and maybe have breaking changes on your pipelines. Please refer to this release note and create ticket if you found an issue.

https://github.com/rdagumampan/yuniql/releases/tag/v0.465.0

Thanks for your interest with yuniql.
Cheers, Rodel
