### ISSUE TITLE
Environment aware does not seem to function in Azure CI/CD 

### ISSUE THREAD

**Issue by djshaw01** [rdagumampan/yuniql#95]
passing --environment in the Additional Arguments text field (eg --environment development) results in yuniql being called like:
C:\hostedtoolcache\windows\yuniql\0.0.0\x64\yuniql.exe run -p D:\a\r1\a\_SHI.Postgres.Schema -c "Server=********.postgres.database.azure.com;Database=shimspint;Port=5432;User Id=***;Password=***;Ssl Mode=Require;" --platform postgresql --delimiter , "--environment development"

where "--environment development" results in an error from the run task:
Option 'environment development' is unknown.

**Comment by rdagumampan** [comment]
Hi @djshaw01 , thanks for reaching out and your interest with yuniql.

I tried first to reproduce with v0.350.0. This is so far working and supports `--environment` parameter.

```console

yuniql --version
yuniql 0.350.0

yuniql run --help

...
...
 --environment              Environment code for environment-aware scripts.
...
...

git clone https://github.com/rdagumampan/yuniql.git c:\temp\yuniql-issue-95

# move all sql files in v0.00 into _developer folder

docker run -e POSTGRES_USER=sa -e POSTGRES_PASSWORD=P@ssw0rd! -e POSTGRES_DB=helloyuniql -p 5432:5432 postgres
SETX YUNIQL_CONNECTION_STRING "Host=localhost;Port=5432;Username=sa;Password=P@ssw0rd!;Database=helloyuniql"

cd c:\temp\yuniql-issue-95\samples\basic-postgresql-sample
yuniql run --platform postgresql -a --environment development
yuniql info --platform postgresql
```

![image](https://user-images.githubusercontent.com/5895952/82377673-53951200-9a24-11ea-8e04-2db0b3eb015c.png)

![image](https://user-images.githubusercontent.com/5895952/82377750-70314a00-9a24-11ea-92cc-e6ee34a6f65f.png)

**Comment by djshaw01** [comment]
Correct (command line works perfectly!)... BTW, This is really awesome and amazing software!.
However:  I'm having problems with the Yuniql Run task in azure DevOps (release pipeline).
![image](https://user-images.githubusercontent.com/1314045/82378261-d604de00-99f2-11ea-8dc8-b0d66fa800fe.png)
![image](https://user-images.githubusercontent.com/1314045/82378325-ec129e80-99f2-11ea-97c6-e770104a5872.png)

**Comment by rdagumampan** [comment]
Yes.. i just first tried if its bug in the core services. It seems to be limited to the way I captured the extra parameters. I can confirm this is a bug.

Meanwhile, please use `dotnet global tool` install if you can via Command Line Task.

```
dotnet tool install -g yuniql.cli
yuniql version
```

**Comment by rdagumampan** [comment]
@djshaw01, 

I have just release a patch that resolved this bug. Please update your extensions to v.0.180.0.
Thanks for reporting the issue. 

Refer to this test run.
![image](https://user-images.githubusercontent.com/5895952/82590769-8ebb5080-9b9e-11ea-99af-e63a23ecedc6.png)

P.S. Appreciate if you can extend support by:
- Clicking the Star button
- Writing few words in in [devops marketplace](https://marketplace.visualstudio.com/items?itemName=rdagumampan.yuniql-azdevops-extensions&ssr=false#review-details)

Cheers, Ardi

**Comment by djshaw01** [comment]
New version was automatically available!  works perfectly.

Thank you so much.
Cheers!

**Comment by rdagumampan** [comment]
@djshaw01 ,

FYI, I have just release v0.465.0. This is a BETA RELEASE and maybe have breaking changes on your pipelines. Please refer to this release note and create ticket if you found an issue.

https://github.com/rdagumampan/yuniql/releases/tag/v0.465.0

Thanks for your interest with yuniql.
Cheers, Rodel

**Comment by djshaw01** [comment]
@rdagumampan thanks so much.  have verified the changes made do not affect my current deployments.  

Kind Regards
Daniel
